### ISSUE TITLE
Updater pinging needs to be updated to utilize InetAddress isReachable() function.

### ISSUE THREAD

**Issue by euphzji** [blackdoor/DAC#31]
Currently, pingNeighbors sends ping RPCs to all neighbors in the AddressTable. This overhead can be lessened by using isReachable to avoid sending RPCs to offline nodes.

**Comment by ykravtsov** [comment]
public boolean isReachable(int timeout) is not a good method for seeing if node is online because it dose not take a port and dose not work very well
